import { Dribble, Facebook, Toko, Spotify, Paypal } from "../assets/images";

export const JobList = [
    {
        id: "1",
        img: Dribble,
        company: "Dribble",
        post: "Front-end Developer",
        category: "development",
        hours: "Full Time",
        city: "San Antonio",
        salary: "130k-160k",
        date: "October 25, 2022",
    },
    {
        id: "2",
        img: Dribble,
        company: "Dribble",
        post: "Backend Developer",
        category: "development",
        hours: "Full Time",
        city: "Dallas",
        salary: "50k-70k",
        date: "October 25, 2022",
    },
    {
        id: "3",
        img: Toko,
        company: "Tokopedia",
        post: "Scrum Master",
        category: "Marketing",
        hours: "Part Time",
        city: "San Antonio",
        salary: "130k-160k",
        date: "March 30, 2021",
    },
    {
        id: "4",
        img: Facebook,
        company: "Facebook",
        post: "Lead Technical Architect",
        category: "Technology",
        hours: "Full Time",
        city: "Melbourne",
        salary: "210k-240k",
        date: "March 30, 2021",
    },
    {
        id: "5",
        img: Spotify,
        company: "Spotify",
        post: "Digital Media Strategist",
        category: "Business",
        hours: "Casual",
        city: "New York",
        salary: "50k-70k",
        date: "March 30, 2021",
    },
    {
        id: "6",
        img: Paypal,
        company: "Paypal",
        post: "Systems Administrator",
        category: "Business",
        hours: "Casual",
        city: "California",
        salary: "40k-50k",
        date: "March 30, 2021",
    },
];
